-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ADMIN USERS TABLE (Whitelist)
create table if not exists admin_users (
  id uuid primary key default uuid_generate_v4(),
  email text unique not null,
  name text,
  role text default 'admin',
  created_at timestamp with time zone default now()
);
alter table admin_users disable row level security;

-- Create ENUM types inside a DO block to handle "already exists" errors
do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type user_role as enum ('citizen', 'officer', 'admin');
  end if;
  if not exists (select 1 from pg_type where typname = 'complaint_status') then
    create type complaint_status as enum ('Pending', 'In Progress', 'Resolved', 'Rejected');
  end if;
end $$;

-- Create Departments Table
create table if not exists departments (
    id bigint generated by default as identity primary key,
    name text unique not null,
    type text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Custom Users Table (extends Supabase auth.users)
create table if not exists public.profiles (
    id uuid references auth.users on delete cascade primary key,
    email text unique not null,
    full_name text,
    role user_role default 'citizen',
    department_id bigint references departments(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Complaints Table
create table if not exists complaints (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) not null,
    department_id bigint references departments(id),
    title text not null,
    description text not null,
    status complaint_status default 'Pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Complaint Updates/Remarks Table
create table if not exists complaint_updates (
    id bigint generated by default as identity primary key,
    complaint_id bigint references complaints(id) on delete cascade not null,
    updated_by uuid references public.profiles(id),
    comment text,
    status complaint_status,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Workers Table
create table if not exists workers (
    id uuid primary key default uuid_generate_v4(),
    name text not null,
    email text unique not null,
    department_id bigint references departments(id),
    worker_id text unique,
    password_hash text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS) Policies
alter table public.profiles enable row level security;
alter table complaints enable row level security;
alter table departments enable row level security;
alter table complaint_updates enable row level security;
alter table workers enable row level security;

-- Policy: Allow everything for now (Backend will handle logic)
-- Using DO block to handle "already exists" for policies as well
do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'profiles') then
    create policy "Enable all access for all users" on public.profiles for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'complaints') then
    create policy "Enable all access for all users" on complaints for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'departments') then
    create policy "Enable all access for all users" on departments for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'complaint_updates') then
    create policy "Enable all access for all users" on complaint_updates for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'workers') then
    create policy "Enable all access for all users" on workers for all using (true) with check (true);
  end if;
end $$;

-- Insert some default departments
insert into departments (name, type) values 
('Sanitation', 'maintenance'),
('Roads & Infrastructure', 'road'),
('Water Supply', 'water'),
('Electricity', 'electrical'),
('Health', 'health'),
('Police Department', 'police')
on conflict (name) do update set type = excluded.type;
