-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create ENUM types (Idempotent)
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        create type user_role as enum ('citizen', 'admin'); -- Worker is separate based on requirements
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'complaint_status') THEN
        create type complaint_status as enum ('Pending', 'Assigned', 'In Progress', 'Completed', 'Rejected');
    END IF;
END $$;

-- 1. Departments Table
create table if not exists departments (
    id bigint generated by default as identity primary key,
    name text unique not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Users Table (Citizens & Admins - Linked to Supabase Auth)
create table if not exists public.users (
    id uuid references auth.users on delete cascade primary key,
    email text unique not null,
    full_name text,
    role user_role default 'citizen',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Workers Table (Separate Login System as requested: Worker ID + Password)
-- Ideally this would also be linked to auth.users, but following spec:
create table if not exists workers (
    id bigint generated by default as identity primary key,
    name text not null,
    worker_id text unique not null, -- Login ID
    password_hash text not null, -- Store hashed passwords
    department_id bigint references departments(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Complaints Table
create table if not exists complaints (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id) not null,
    department_id bigint references departments(id),
    title text not null,
    description text not null,
    status complaint_status default 'Pending',
    location_lat double precision,
    location_lng double precision,
    assigned_worker_id bigint references workers(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Complaint Images Table (Before/After)
create table if not exists complaint_images (
    id bigint generated by default as identity primary key,
    complaint_id bigint references complaints(id) on delete cascade not null,
    image_url text not null,
    type text check (type in ('before', 'after')), -- discriminator
    uploaded_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Notifications Table
create table if not exists notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id) not null,
    message text not null,
    read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Audit Logs (Optional but good for Admin)
create table if not exists audit_logs (
    id bigint generated by default as identity primary key,
    action text not null,
    performed_by uuid references auth.users(id), -- Nullable if system or worker
    details jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.users enable row level security;
alter table workers enable row level security;
alter table complaints enable row level security;
alter table complaint_images enable row level security;
alter table notifications enable row level security;

-- Basic Policies (Open for now to facilitate development, can be tightened later)
-- Users
drop policy if exists "Enable access to own user data" on public.users;
create policy "Enable access to own user data" on public.users for select using (auth.uid() = id);
-- Allow insert during registration
drop policy if exists "Enable insert for registration" on public.users;
create policy "Enable insert for registration" on public.users for insert with check (auth.uid() = id);

-- Public Read for Departments
alter table departments enable row level security;
drop policy if exists "Public read departments" on departments;
create policy "Public read departments" on departments for select using (true);

-- Complaints (Viewable by owner and admins/workers)
drop policy if exists "Users can see own complaints" on complaints;
create policy "Users can see own complaints" on complaints for select using (auth.uid() = user_id);

drop policy if exists "Users can insert complaints" on complaints;
create policy "Users can insert complaints" on complaints for insert with check (auth.uid() = user_id);

-- Insert Default Departments
insert into departments (name) values 
('Sanitation'),
('Roads & Infrastructure'),
('Water Supply'),
('Electricity'),
('Health')
on conflict (name) do nothing;
